### ISSUE TITLE
Issue detected while Building

### ISSUE THREAD

**Issue by Dhanesh-raj** [cybergalactic/PythonVehicleSimulator#10]
**GitHub does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found **
when I run both 

1. pip install -e . /home/oceannet/Documents/GitHub/PythonVehicleSimulator 
2. !pip install git+https://github.com/cybergalactic/PythonVehicleSimulator.git
Unable to install on local system

Also an error arised due to 

        WARNING: The user site-packages directory is disabled.
        /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        error: can't create or remove files in install directory

**Comment by cybergalactic** [comment]
The package is configured for a modern Python packaging approach, using a build system specified by pyproject.toml and setup.cfg. Navigate to the directory where your pyproject.toml and setup.cfg files are located using

  cd  mypath/PythonVehicleSimulator 

Then run

  pip install -e .

**Comment by Dhanesh-raj** [comment]
Issue resolved .
