### ISSUE TITLE
Remus 100 Model Adding Integrator Error Term Twice 

### ISSUE THREAD

**Issue by grayson-woods** [cybergalactic/PythonVehicleSimulator#11]
It appears the `remus100.py` `depthHeadingAutopilot` controller might be adding the integrator error term twice. It uses `ssa` to calculate the integrator error after calling `PIDPolePlacement` below:

https://github.com/cybergalactic/PythonVehicleSimulator/blob/7658c53f713502e0829acd60934dbdf21756fb52/src/python_vehicle_simulator/vehicles/remus100.py#L489

but `PIDPolePlacement` internally adds the integrator error term and returns that value as `self.e_psi_int`:

https://github.com/cybergalactic/PythonVehicleSimulator/blob/7658c53f713502e0829acd60934dbdf21756fb52/src/python_vehicle_simulator/lib/control.py#L46

I might be misunderstanding something, but it seems that this might be causing `remus100` to effectively double the effect of the integrator term.

**Comment by cybergalactic** [comment]
Thanks for sharing this information. You are, of course, right. The integral term should not be propagated in the remus100.py file.  

An index error in the matrix C has also been corrected. This is a minor bug in the hydrodynamic model not related to this issue. 

Anyway, none of these updates seems to cause a significant change in the response.  The file on GitHub has been updated accordingly.

**Comment by grayson-woods** [comment]
Thank you for the quick response!
