### ISSUE TITLE
Why is the 1/2 not needed in the displacement formula?

### ISSUE THREAD

**Issue by nanqiangyipo** [cybergalactic/PythonVehicleSimulator#14]
displacement formula in uniformly accelerated linear motion :
s_t = v_0\*t + 0.5\*a\*t^2 

I read the `remus100.dynamics` and `gnc.attitudeEuler` codes，the displacement formula  in codes  is 
s_t = v_0\*t +a\*t^2

in  `remus100.dynamics`  codes:
v_t = v_0 + a\*t
![vt](https://github.com/user-attachments/assets/44a49bdb-75b6-44c6-a77d-36f99c2aa8a5)

in `gnc.attitudeEuler` codes:
p_t = p_0 + s_t = p_0 + (v_t\*t) = p_0 + (v_0\*t +a*t^2)
I think 0.5 is missing here
![st](https://github.com/user-attachments/assets/66e1d1e5-1206-4bcd-8fc9-b5eb805d70e6)

**Comment by cybergalactic** [comment]
On the internet, the formula

s_t = v_0*t + 0.5*a*t^2

is frequently used. However, this formula assumes that a = constant or at least nearly constant. Then  you integrate

v_t = v_0 + a*t,   a = constant

to get s_t = v_0*t + 0.5*a*t^2. Many numerical methods are available for time-varying systems, including time-varying acceleration, when solving differential equations. The Python code uses Euler's forward method, which is sensitive to oscillations, such as ocean waves.

https://en.wikipedia.org/wiki/Euler_method

The recommended method is RK4 if you want to improve accuracy.  

https://en.wikipedia.org/wiki/Runge–Kutta_methods#The_Runge–Kutta_method

My textbook describes all these methods in the appendix for numerical methods.  Note that the m-file version of the code (MSS library) uses RK4, not Euler's method. I plan to update this for the Python code in the future.

**Comment by nanqiangyipo** [comment]
I understand now.
I’ve learned a lot through your work. Thank you very much.
