### ISSUE TITLE
Plotting coordinates in the NED frame

### ISSUE THREAD

**Issue by jsalfity** [cybergalactic/PythonVehicleSimulator#5]
This may be all a lack of my understanding of marine vehicles, but I'm hung up on what appears to be an issue.

Regarding plotting coordinates and trajectories in `plotTimeSeries.py`.

Here:
https://github.com/cybergalactic/PythonVehicleSimulator/blob/323cc736341b438ad627b840f495fce524902cff/src/python_vehicle_simulator/lib/plotTimeSeries.py#L68

and here:
https://github.com/cybergalactic/PythonVehicleSimulator/blob/323cc736341b438ad627b840f495fce524902cff/src/python_vehicle_simulator/lib/plotTimeSeries.py#L184

Why are the x-y coordinates flipped ?

For example, a trajectory with a final state vector of 
```sh
[[ 1.17621619e+01]
 [-3.37899219e+00]
 [ 2.09040400e-02]
 [-2.77784460e-05]
 [-1.13410903e-01]
 [ 1.75338625e+00]
 [-1.94627061e-01]
 [-2.53396261e-01]
 [ 2.21638276e-02]
 [-7.35479426e-05]
 [-8.51040706e-06]
 [-6.60679880e-04]]
```
meaning that `x=11.76` and `y=-3.37`, show a flipped x-y coordinates, according to the axis labels, in the plots produced by the aforementioned functions.

<img width="450" alt="Screen Shot 2022-07-22 at 3 34 15 PM" src="https://user-images.githubusercontent.com/20803806/180559624-9ccc71dd-39f2-41f8-986e-f367f171ee25.png">

<img width="582" alt="Screen Shot 2022-07-22 at 3 31 15 PM" src="https://user-images.githubusercontent.com/20803806/180557387-a56bf5b1-d8c0-4730-ac2a-f5489cfdb0fc.png">

**Comment by cybergalactic** [comment]
The explanation is simple. Most people prefer to plot North upwards and East to the right to mimick a map. Hence, you must plot the yx-coordinates instead of the xy-coordinates. Remember x = North (y-axis),   y = East (x-axis), and z = Down.

**Comment by jsalfity** [comment]
Thank you!
