### ISSUE TITLE
remus100.py

### ISSUE THREAD

**Issue by beatastic** [cybergalactic/PythonVehicleSimulator#7]
In the remus100.py, you have the following code section:

        # Tail rudder parameters (single)
        [...]
        self.A_r = 0.10 * 0.05      # rudder area (m2)
        [...]

        # Stern-plane paramaters (double)
        [...]
        self.A_s = 2 * 0.10 * 0.05  # stern-plane area (m2)
        [...]

If I understand the remus 100 vehicle properly (and I probably don't!), then the top and bottom halves of the rudder are both actuatable?  Wouldn't the self.A_r be set to 2 * 0.010 * 0.05 just as for the stern planes?  What am I missing here?

Thanks!

**Comment by cybergalactic** [comment]
You are correct. It makes sense to multiply A_r by the factor 2. Note that the area A = 0.10 * 0.05 is a rough estimate. This number should also be updated if you can access one of the Remus 100 vehicles and measure the rudder area more accurately.

**Comment by beatastic** [comment]
Thank you!  If I can scrounge some verified measurements, I will share them.
