### ISSUE TITLE
Free falling?

### ISSUE THREAD

**Issue by huisky2000** [cybergalactic/PythonVehicleSimulator#9]
Hi,

Sorry to mention this again here. I meant to use the Python module of MSS to simulate the free falling. I tried to use case 9 as an example. I made the following changes:
1. set rpm to zero (main.py), such as 'remus100('depthHeadingAutopilot',30,0,0,0.5,0)'.
2. set the velocity vector self.nu (remus100.py) with a downward velocity (positive z?), 'self.nu = np.array([3, 0, 3, 0, 0, 0], float) # velocity vector'
3. set the buoyancy to be less than the weight (remus100.py), self.B=self.W*0.2

However, I don't see a free-falling of the object; the max depth is about 0.8 m. Is there something else I should change?
It seems that the initial velocity of the object has no impact to the results and also wondering is it possible to set the initial position of the object (e.g. with an inclination angle)?

Regards
Huisky

**Comment by cybergalactic** [comment]
You need to turn off the control systems (three autopilots). You should remove all code for depth, heading, and speed control or simply multiply the resulting force by 0 such that

    tau_sum = 0 * tau + tau_liftdrag + tau_crossflow - np.matmul(C+D,nu_r) 

If you keep the autopilot code in the script you will see that the control system produces "dummy" forces in the plots, but they do not affect the AUV dynamics.  

Finally, you must also change the buoyancy term, e.g.,  

   self.B = 0.9*self.W

Then your AUV will fall like a rock.
